/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import photousac.JPEGHandler;
import java.awt.Toolkit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import photousac.BMPtoJPEGImage;
import photousac.ImageHandler;
import photousac.JPEGImageCopy;
import photousac.JPEGImageHandlerColors;
import photousac.JPEGImageHandlerColors2;
import photousac.JPEGImageHandlerColors3;
import photousac.JPEGImageHandlerColors4;
import photousac.JPEGtoBMPImage;
import photousac.PEGImageHandlerBN;
import photousac.PEGImageHandlerRotator;
import photousac.PEGImageHandlerRotator2;

/**
 *
 * @author telma
 */
public class JFConvertidor extends javax.swing.JFrame {

    public String Ruta;

    public JFConvertidor() {
        initComponents();
        JlblRuta.setText(Ruta);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jRadioJpegtoBmp = new javax.swing.JRadioButton();
        jRadioBmptoJpeg = new javax.swing.JRadioButton();
        jRadioBCopia = new javax.swing.JRadioButton();
        RdbColors = new javax.swing.JRadioButton();
        jRadioRotar = new javax.swing.JRadioButton();
        jRadioBBN = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        JlblRuta = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jRadioJpegtoBmp.setText("JPEG a BMP  ");

        jRadioBmptoJpeg.setText("BMP a JPEG");

        jRadioBCopia.setText("Copiar JPEG");

        RdbColors.setText("Rojo, Verde, Azul y sephia");

        jRadioRotar.setText("Rotar");

        jRadioBBN.setText("Blanco y Negro");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioBmptoJpeg)
                    .addComponent(jRadioBCopia)
                    .addComponent(RdbColors)
                    .addComponent(jRadioRotar)
                    .addComponent(jRadioJpegtoBmp, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioBBN))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jRadioJpegtoBmp)
                .addGap(18, 18, 18)
                .addComponent(jRadioBmptoJpeg)
                .addGap(18, 18, 18)
                .addComponent(jRadioBCopia)
                .addGap(18, 18, 18)
                .addComponent(RdbColors)
                .addGap(18, 18, 18)
                .addComponent(jRadioRotar)
                .addGap(18, 18, 18)
                .addComponent(jRadioBBN)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jButton1.setText("Ejecutar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Seleccionar Imagen");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Salir");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(JlblRuta, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(115, 115, 115)
                        .addComponent(jButton2)))
                .addContainerGap(100, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(18, 18, 18))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JlblRuta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton3))
                .addGap(10, 10, 10))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        ImageHandler j = new JPEGtoBMPImage(Ruta);
        ImageHandler b = new BMPtoJPEGImage(Ruta);
        ImageHandler c = new JPEGImageCopy(Ruta);
        ImageHandler Color = new JPEGImageHandlerColors(Ruta);
        ImageHandler ColorV = new JPEGImageHandlerColors2(Ruta);
        ImageHandler ColorB = new JPEGImageHandlerColors3(Ruta);
        ImageHandler ColorS = new JPEGImageHandlerColors4(Ruta);
        ImageHandler R = new PEGImageHandlerRotator(Ruta);
        ImageHandler R2 = new PEGImageHandlerRotator2(Ruta);
        ImageHandler BW = new PEGImageHandlerBN(Ruta);

        JlblRuta.setText(Ruta);

        if (jRadioJpegtoBmp.isSelected() == true) {

            try {

                j.generateFiles();

            } catch (Exception ex) {
                Logger.getLogger(JFConvertidor.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {

            } catch (Exception ex) {
                Logger.getLogger(JFConvertidor.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
        if (jRadioBmptoJpeg.isSelected() == true) {

            try {

                b.generateFiles();

            } catch (Exception ex) {
                Logger.getLogger(JFConvertidor.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        if (jRadioBCopia.isSelected() == true) {

            try {
                c.generateFiles();

            } catch (Exception ex) {
                Logger.getLogger(JFConvertidor.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

        if (RdbColors.isSelected() == true) {
            try {
                Color.generateFiles();
            } catch (Exception ex) {
                Logger.getLogger(JFConvertidor.class.getName()).log(Level.SEVERE, null, ex);
            }

            try {
                ColorV.generateFiles();
            } catch (Exception ex) {
                Logger.getLogger(JFConvertidor.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                ColorB.generateFiles();
            } catch (Exception ex) {
                Logger.getLogger(JFConvertidor.class.getName()).log(Level.SEVERE, null, ex);
            }

            try {
                ColorS.generateFiles();
            } catch (Exception ex) {
                Logger.getLogger(JFConvertidor.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
        if (jRadioRotar.isSelected() == true) {
            try {
                R.generateFiles();
            } catch (Exception ex) {
                Logger.getLogger(JFConvertidor.class.getName()).log(Level.SEVERE, null, ex);
            }

            try {
                R2.generateFiles();
            } catch (Exception ex) {
                Logger.getLogger(JFConvertidor.class.getName()).log(Level.SEVERE, null, ex);
            }

        }

        if (jRadioBBN.isSelected() == true) {
            try {
                BW.generateFiles();
            } catch (Exception ex) {
                Logger.getLogger(JFConvertidor.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        JFileChooser fc = new JFileChooser();
        FileNameExtensionFilter extencion = new FileNameExtensionFilter("Seleccionar una imagen", "jpg", "bmp");
        fc.setFileFilter(extencion);
        if (fc.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            Toolkit tool = Toolkit.getDefaultToolkit();
            String ruta = fc.getSelectedFile().toString();
            Ruta = ruta;
            JlblRuta.setText(Ruta);
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.setVisible(false);
        JFPrincipal p = new JFPrincipal();
        p.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFConvertidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFConvertidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFConvertidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFConvertidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFConvertidor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JlblRuta;
    private javax.swing.JRadioButton RdbColors;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioBBN;
    private javax.swing.JRadioButton jRadioBCopia;
    private javax.swing.JRadioButton jRadioBmptoJpeg;
    private javax.swing.JRadioButton jRadioJpegtoBmp;
    private javax.swing.JRadioButton jRadioRotar;
    // End of variables declaration//GEN-END:variables
}
